const defaultPreference = {
  smite: {
    structure: 'preference',
    data: {
      1: {
        id: 1,
        name: 'Agni',
        value: 3,
        slug: 'agni',
      },
      2: {
        id: 2,
        name: 'Anubis',
        value: 3,
        slug: 'anubis',
      },
      3: {
        id: 3,
        name: 'Arachne',
        value: 3,
        slug: 'arachne',
      },
      4: {
        id: 4,
        name: 'Artemis',
        value: 3,
        slug: 'artemis',
      },
      5: {
        id: 5,
        name: 'Bastet',
        value: 3,
        slug: 'bastet',
      },
      6: {
        id: 6,
        name: 'Hades',
        value: 3,
        slug: 'hades',
      },
      7: {
        id: 7,
        name: 'He Bo',
        value: 3,
        slug: 'he-bo',
      },
      8: {
        id: 8,
        name: 'Hel',
        value: 3,
        slug: 'hel',
      },
      9: {
        id: 9,
        name: 'Hun Batz',
        value: 3,
        slug: 'hun-batz',
      },
      10: {
        id: 10,
        name: 'Kali',
        value: 3,
        slug: 'kali',
      },
      11: {
        id: 11,
        name: 'Kukulkan',
        value: 3,
        slug: 'kukulkan',
      },
      12: {
        id: 12,
        name: 'Odin',
        value: 3,
        slug: 'odin',
      },
      13: {
        id: 13,
        name: 'Ra',
        value: 3,
        slug: 'ra',
      },
      14: {
        id: 14,
        name: 'Sobek',
        value: 3,
        slug: 'sobek',
      },
      15: {
        id: 15,
        name: 'Vamana',
        value: 3,
        slug: 'vamana',
      },
      16: {
        id: 16,
        name: 'Ymir',
        value: 3,
        slug: 'ymir',
      },
      17: {
        id: 17,
        name: 'Zeus',
        value: 3,
        slug: 'zeus',
      },
      18: {
        id: 18,
        name: 'Guan Yu',
        value: 3,
        slug: 'guan-yu',
      },
      19: {
        id: 19,
        name: 'Bakasura',
        value: 3,
        slug: 'bakasura',
      },
      20: {
        id: 20,
        name: 'Anhur',
        value: 3,
        slug: 'anhur',
      },
      21: {
        id: 21,
        name: 'Cupid',
        value: 3,
        slug: 'cupid',
      },
      22: {
        id: 22,
        name: 'Thor',
        value: 3,
        slug: 'thor',
      },
      23: {
        id: 23,
        name: 'Ares',
        value: 3,
        slug: 'ares',
      },
      24: {
        id: 24,
        name: 'Freya',
        value: 3,
        slug: 'freya',
      },
      25: {
        id: 25,
        name: 'Loki',
        value: 3,
        slug: 'loki',
      },
      26: {
        id: 26,
        name: 'Bacchus',
        value: 3,
        slug: 'bacchus',
      },
      27: {
        id: 27,
        name: 'Xbalanque',
        value: 3,
        slug: 'xbalanque',
      },
      28: {
        id: 28,
        name: 'Hercules',
        value: 3,
        slug: 'hercules',
      },
      29: {
        id: 29,
        name: 'Vulcan',
        value: 3,
        slug: 'vulcan',
      },
      30: {
        id: 30,
        name: 'Neith',
        value: 3,
        slug: 'neith',
      },
      31: {
        id: 31,
        name: 'Poseidon',
        value: 3,
        slug: 'poseidon',
      },
      32: {
        id: 32,
        name: 'Aphrodite',
        value: 3,
        slug: 'aphrodite',
      },
      33: {
        id: 33,
        name: 'Apollo',
        value: 3,
        slug: 'apollo',
      },
      34: {
        id: 34,
        name: 'Ne Zha',
        value: 3,
        slug: 'ne-zha',
      },
      35: {
        id: 35,
        name: 'Fenrir',
        value: 3,
        slug: 'fenrir',
      },
      36: {
        id: 36,
        name: 'Isis',
        value: 3,
        slug: 'isis',
      },
      37: {
        id: 37,
        name: 'Athena',
        value: 3,
        slug: 'athena',
      },
      38: {
        id: 38,
        name: 'Chronos',
        value: 3,
        slug: 'chronos',
      },
      39: {
        id: 39,
        name: "Chang'e",
        value: 3,
        slug: 'chang-e',
      },
      40: {
        id: 40,
        name: 'Tyr',
        value: 3,
        slug: 'tyr',
      },
      41: {
        id: 41,
        name: 'Zhong Kui',
        value: 3,
        slug: 'zhong-kui',
      },
      42: {
        id: 42,
        name: 'Thanatos',
        value: 3,
        slug: 'thanatos',
      },
      43: {
        id: 43,
        name: 'Mercury',
        value: 3,
        slug: 'mercury',
      },
      44: {
        id: 44,
        name: 'Sun Wukong',
        value: 3,
        slug: 'sun-wukong',
      },
      45: {
        id: 45,
        name: 'Ah Muzen Cab',
        value: 3,
        slug: 'ah-muzen-cab',
      },
      46: {
        id: 46,
        name: 'Nu Wa',
        value: 3,
        slug: 'nu-wa',
      },
      47: {
        id: 47,
        name: 'Chaac',
        value: 3,
        slug: 'chaac',
      },
      48: {
        id: 48,
        name: 'Geb',
        value: 3,
        slug: 'geb',
      },
      49: {
        id: 49,
        name: 'Nemesis',
        value: 3,
        slug: 'nemesis',
      },
      50: {
        id: 50,
        name: 'Scylla',
        value: 3,
        slug: 'scylla',
      },
      51: {
        id: 51,
        name: 'Ullr',
        value: 3,
        slug: 'ullr',
      },
      52: {
        id: 52,
        name: 'Kumbhakarna',
        value: 3,
        slug: 'kumbhakarna',
      },
      53: {
        id: 53,
        name: 'Osiris',
        value: 3,
        slug: 'osiris',
      },
      54: {
        id: 54,
        name: 'Janus',
        value: 3,
        slug: 'janus',
      },
      55: {
        id: 55,
        name: 'Rama',
        value: 3,
        slug: 'rama',
      },
      56: {
        id: 56,
        name: 'Serqet',
        value: 3,
        slug: 'serqet',
      },
      57: {
        id: 57,
        name: 'Cabrakan',
        value: 3,
        slug: 'cabrakan',
      },
      58: {
        id: 58,
        name: 'Sylvanus',
        value: 3,
        slug: 'sylvanus',
      },
      59: {
        id: 59,
        name: 'Nox',
        value: 3,
        slug: 'nox',
      },
      60: {
        id: 60,
        name: 'Ao Kuang',
        value: 3,
        slug: 'ao-kuang',
      },
      61: {
        id: 61,
        name: 'Awilix',
        value: 3,
        slug: 'awilix',
      },
      62: {
        id: 62,
        name: 'HouYi',
        value: 3,
        slug: 'hou-yi',
      },
      63: {
        id: 63,
        name: 'Bellona',
        value: 3,
        slug: 'bellona',
      },
      64: {
        id: 64,
        name: 'Medusa',
        value: 3,
        slug: 'medusa',
      },
      65: {
        id: 65,
        name: 'Ah Puch',
        value: 3,
        slug: 'ah-puch',
      },
      66: {
        id: 66,
        name: 'Ratatoskr',
        value: 3,
        slug: 'ratatoskr',
      },
      67: {
        id: 67,
        name: 'Ravana',
        value: 3,
        slug: 'ravana',
      },
      68: {
        id: 68,
        name: 'Khepri',
        value: 3,
        slug: 'khepri',
      },
      69: {
        id: 69,
        name: 'Xing Tian',
        value: 3,
        slug: 'xing-tian',
      },
      70: {
        id: 70,
        name: 'Sol',
        value: 3,
        slug: 'sol',
      },
      71: {
        id: 71,
        name: 'Chiron',
        value: 3,
        slug: 'chiron',
      },
      72: {
        id: 72,
        name: 'Amaterasu',
        value: 3,
        slug: 'amaterasu',
      },
      73: {
        id: 73,
        name: 'Raijin',
        value: 3,
        slug: 'raijin',
      },
      74: {
        id: 74,
        name: 'Skadi',
        value: 3,
        slug: 'skadi',
      },
      75: {
        id: 75,
        name: 'Jing Wei',
        value: 3,
        slug: 'jing-wei',
      },
      76: {
        id: 76,
        name: 'Susano',
        value: 3,
        slug: 'susano',
      },
      77: {
        id: 77,
        name: 'Fafnir',
        value: 3,
        slug: 'fafnir',
      },
      78: {
        id: 78,
        name: 'Erlang Shen',
        value: 3,
        slug: 'erlang-shen',
      },
      79: {
        id: 79,
        name: 'Terra',
        value: 3,
        slug: 'terra',
      },
      80: {
        id: 80,
        name: 'Izanami',
        value: 3,
        slug: 'izanami',
      },
      81: {
        id: 81,
        name: 'Camazotz',
        value: 3,
        slug: 'camazotz',
      },
      82: {
        id: 82,
        name: 'Thoth',
        value: 3,
        slug: 'thoth',
      },
      83: {
        id: 83,
        name: 'Nike',
        value: 3,
        slug: 'nike',
      },
      84: {
        id: 84,
        name: 'The Morrigan',
        value: 3,
        slug: 'the-morrigan',
      },
      85: {
        id: 85,
        name: 'Kuzenbo',
        value: 3,
        slug: 'kuzenbo',
      },
      86: {
        id: 86,
        name: 'Cernunnos',
        value: 3,
        slug: 'cernunnos',
      },
      87: {
        id: 87,
        name: 'Ganesha',
        value: 3,
        slug: 'ganesha',
      },
      88: {
        id: 88,
        name: 'Da Ji',
        value: 3,
        slug: 'da-ji',
      },
      89: {
        id: 89,
        name: 'Cu Chulainn',
        value: 3,
        slug: 'cu-chulainn',
      },
      90: {
        id: 90,
        name: 'Artio',
        value: 3,
        slug: 'artio',
      },
      91: {
        id: 91,
        name: 'Hachiman',
        value: 3,
        slug: 'hachiman',
      },
      92: {
        id: 92,
        name: 'Discordia',
        value: 3,
        slug: 'discordia',
      },
      93: {
        id: 93,
        name: 'Cerberus',
        value: 3,
        slug: 'cerberus',
      },
      94: {
        id: 94,
        name: 'Achilles',
        value: 3,
        slug: 'achilles',
      },
      95: {
        id: 95,
        name: 'Chernobog',
        value: 3,
        slug: 'chernobog',
      },
      96: {
        id: 96,
        name: 'Baron Samedi',
        value: 3,
        slug: 'baron-samedi',
      },
      97: {
        id: 97,
        name: 'Pele',
        value: 3,
        slug: 'pele',
      },
      98: {
        id: 98,
        name: 'Hera',
        value: 3,
        slug: 'hera',
      },
      99: {
        id: 99,
        name: 'King Arthur',
        value: 3,
        slug: 'king-arthur',
      },
      100: {
        id: 100,
        name: 'Merlin',
        value: 3,
        slug: 'merlin',
      },
      101: {
        id: 101,
        name: 'Jormungandr',
        value: 3,
        slug: 'jormungandr',
      },
      102: {
        id: 102,
        name: 'Horus',
        value: 3,
        slug: 'horus',
      },
      103: {
        id: 103,
        name: 'Set',
        value: 3,
        slug: 'set',
      },
      104: {
        id: 104,
        name: 'Olorun',
        value: 3,
        slug: 'olorun',
      },
      105: {
        id: 105,
        name: 'Persephone',
        value: 3,
        slug: 'persephone',
      },
      106: {
        id: 106,
        name: 'Yemoja',
        value: 3,
        slug: 'yemoja',
      },
      107: {
        id: 107,
        name: 'Heimdallr',
        value: 3,
        slug: 'heimdallr',
      },
      108: {
        id: 108,
        name: 'Mulan',
        value: 3,
        slug: 'mulan',
      },
      109: {
        id: 109,
        name: 'Baba Yaga',
        value: 3,
        slug: 'baba-yaga',
      },
      110: {
        id: 110,
        name: 'Cthulhu',
        value: 3,
        slug: 'cthulhu',
      },
    },
  },
  dota: {},
};

export default defaultPreference;
