export default {
  1: {
    id: 1,
    name: "Agni",
    class: "mage",
    damageType: "magical",
    slug: "agni",
    role: {
      carry: 1,
      support: 1,
      mid: 5,
      jungle: 2,
      solo: 1,
    },
  },
  2: {
    id: 2,
    name: "Anubis",
    class: "mage",
    damageType: "magical",
    slug: "anubis",
    role: {
      carry: 1,
      support: 1,
      mid: 5,
      jungle: 3,
      solo: 3,
    },
  },
  3: {
    id: 3,
    name: "Arachne",
    class: "assassin",
    damageType: "physical",
    slug: "arachne",
    role: {
      carry: 2,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 3,
    },
  },
  4: {
    id: 4,
    name: "Artemis",
    class: "hunter",
    damageType: "physical",
    slug: "artemis",
    role: {
      carry: 5,
      support: 1,
      mid: 1,
      jungle: 1,
      solo: 1,
    },
  },
  5: {
    id: 5,
    name: "Bastet",
    class: "assassin",
    damageType: "physical",
    slug: "bastet",
    role: {
      carry: 1,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 2,
    },
  },
  6: {
    id: 6,
    name: "Hades",
    class: "mage",
    damageType: "magical",
    slug: "hades",
    role: {
      carry: 1,
      support: 2,
      mid: 3,
      jungle: 2,
      solo: 4,
    },
  },
  7: {
    id: 7,
    name: "He Bo",
    class: "mage",
    damageType: "magical",
    slug: "he-bo",
    role: {
      carry: 2,
      support: 1,
      mid: 5,
      jungle: 4,
      solo: 3,
    },
  },
  8: {
    id: 8,
    name: "Hel",
    class: "mage",
    damageType: "magical",
    slug: "hel",
    role: {
      carry: 1,
      support: 3,
      mid: 5,
      jungle: 1,
      solo: 3,
    },
  },
  9: {
    id: 9,
    name: "Hun Batz",
    class: "assassin",
    damageType: "physical",
    slug: "hun-batz",
    role: {
      carry: 1,
      support: 2,
      mid: 1,
      jungle: 5,
      solo: 2,
    },
  },
  10: {
    id: 10,
    name: "Kali",
    class: "assassin",
    damageType: "physical",
    slug: "kali",
    role: {
      carry: 3,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 2,
    },
  },
  11: {
    id: 11,
    name: "Kukulkan",
    class: "mage",
    damageType: "magical",
    slug: "kukulkan",
    role: {
      carry: 1,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 1,
    },
  },
  12: {
    id: 12,
    name: "Odin",
    class: "warrior",
    damageType: "physical",
    slug: "odin",
    role: {
      carry: 1,
      support: 3,
      mid: 1,
      jungle: 3,
      solo: 4,
    },
  },
  13: {
    id: 13,
    name: "Ra",
    class: "mage",
    damageType: "magical",
    slug: "ra",
    role: {
      carry: 1,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 2,
    },
  },
  14: {
    id: 14,
    name: "Sobek",
    class: "guardian",
    damageType: "magical",
    slug: "sobek",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 1,
      solo: 4,
    },
  },
  15: {
    id: 15,
    name: "Vamana",
    class: "warrior",
    damageType: "physical",
    slug: "vamana",
    role: {
      carry: 2,
      support: 1,
      mid: 1,
      jungle: 3,
      solo: 5,
    },
  },
  16: {
    id: 16,
    name: "Ymir",
    class: "guardian",
    damageType: "magical",
    slug: "ymir",
    role: {
      carry: 1,
      support: 5,
      mid: 2,
      jungle: 3,
      solo: 3,
    },
  },
  17: {
    id: 17,
    name: "Zeus",
    class: "mage",
    damageType: "magical",
    slug: "zeus",
    role: {
      carry: 1,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 1,
    },
  },
  18: {
    id: 18,
    name: "Guan Yu",
    class: "warrior",
    damageType: "physical",
    slug: "guan-yu",
    role: {
      carry: 1,
      support: 3,
      mid: 1,
      jungle: 3,
      solo: 5,
    },
  },
  19: {
    id: 19,
    name: "Bakasura",
    class: "assassin",
    damageType: "physical",
    slug: "bakasura",
    role: {
      carry: 2,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 3,
    },
  },
  20: {
    id: 20,
    name: "Anhur",
    class: "hunter",
    damageType: "physical",
    slug: "anhur",
    role: {
      carry: 5,
      support: 2,
      mid: 4,
      jungle: 2,
      solo: 1,
    },
  },
  21: {
    id: 21,
    name: "Cupid",
    class: "hunter",
    damageType: "physical",
    slug: "cupid",
    role: {
      carry: 5,
      support: 1,
      mid: 3,
      jungle: 1,
      solo: 1,
    },
  },
  22: {
    id: 22,
    name: "Thor",
    class: "assassin",
    damageType: "physical",
    slug: "thor",
    role: {
      carry: 1,
      support: 2,
      mid: 1,
      jungle: 5,
      solo: 3,
    },
  },
  23: {
    id: 23,
    name: "Ares",
    class: "guardian",
    damageType: "magical",
    slug: "ares",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 2,
      solo: 3,
    },
  },
  24: {
    id: 24,
    name: "Freya",
    class: "mage",
    damageType: "magical",
    slug: "freya",
    role: {
      carry: 5,
      support: 1,
      mid: 1,
      jungle: 2,
      solo: 1,
    },
  },
  25: {
    id: 25,
    name: "Loki",
    class: "assassin",
    damageType: "physical",
    slug: "loki",
    role: {
      carry: 2,
      support: 2,
      mid: 2,
      jungle: 5,
      solo: 4,
    },
  },
  26: {
    id: 26,
    name: "Bacchus",
    class: "guardian",
    damageType: "magical",
    slug: "bacchus",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 2,
      solo: 1,
    },
  },
  27: {
    id: 27,
    name: "Xbalanque",
    class: "hunter",
    damageType: "physical",
    slug: "xbalanque",
    role: {
      carry: 5,
      support: 1,
      mid: 2,
      jungle: 1,
      solo: 1,
    },
  },
  28: {
    id: 28,
    name: "Hercules",
    class: "warrior",
    damageType: "physical",
    slug: "hercules",
    role: {
      carry: 1,
      support: 4,
      mid: 1,
      jungle: 2,
      solo: 5,
    },
  },
  29: {
    id: 29,
    name: "Vulcan",
    class: "mage",
    damageType: "magical",
    slug: "vulcan",
    role: {
      carry: 3,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 3,
    },
  },
  30: {
    id: 30,
    name: "Neith",
    class: "hunter",
    damageType: "physical",
    slug: "neith",
    role: {
      carry: 5,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 2,
    },
  },
  31: {
    id: 31,
    name: "Poseidon",
    class: "mage",
    damageType: "magical",
    slug: "poseidon",
    role: {
      carry: 2,
      support: 1,
      mid: 5,
      jungle: 3,
      solo: 1,
    },
  },
  32: {
    id: 32,
    name: "Aphrodite",
    class: "mage",
    damageType: "magical",
    slug: "aphrodite",
    role: {
      carry: 1,
      support: 2,
      mid: 5,
      jungle: 1,
      solo: 4,
    },
  },
  33: {
    id: 33,
    name: "Apollo",
    class: "hunter",
    damageType: "physical",
    slug: "apollo",
    role: {
      carry: 5,
      support: 1,
      mid: 3,
      jungle: 4,
      solo: 2,
    },
  },
  34: {
    id: 34,
    name: "Ne Zha",
    class: "assassin",
    damageType: "physical",
    slug: "ne-zha",
    role: {
      carry: 1,
      support: 3,
      mid: 1,
      jungle: 5,
      solo: 2,
    },
  },
  35: {
    id: 35,
    name: "Fenrir",
    class: "assassin",
    damageType: "physical",
    slug: "fenrir",
    role: {
      carry: 1,
      support: 3,
      mid: 2,
      jungle: 5,
      solo: 3,
    },
  },
  36: {
    id: 36,
    name: "Isis",
    class: "mage",
    damageType: "magical",
    slug: "isis",
    role: {
      carry: 1,
      support: 2,
      mid: 5,
      jungle: 1,
      solo: 1,
    },
  },
  37: {
    id: 37,
    name: "Athena",
    class: "guardian",
    damageType: "magical",
    slug: "athena",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 4,
      solo: 4,
    },
  },
  38: {
    id: 38,
    name: "Chronos",
    class: "mage",
    damageType: "magical",
    slug: "chronos",
    role: {
      carry: 5,
      support: 1,
      mid: 4,
      jungle: 1,
      solo: 2,
    },
  },
  39: {
    id: 39,
    name: "Chang'e",
    class: "mage",
    damageType: "magical",
    slug: "change",
    role: {
      carry: 1,
      support: 1,
      mid: 5,
      jungle: 3,
      solo: 3,
    },
  },
  40: {
    id: 40,
    name: "Tyr",
    class: "warrior",
    damageType: "physical",
    slug: "tyr",
    role: {
      carry: 1,
      support: 3,
      mid: 1,
      jungle: 3,
      solo: 5,
    },
  },
  41: {
    id: 41,
    name: "Zhong Kui",
    class: "mage",
    damageType: "magical",
    slug: "zhong-kui",
    role: {
      carry: 3,
      support: 1,
      mid: 4,
      jungle: 1,
      solo: 4,
    },
  },
  42: {
    id: 42,
    name: "Thanatos",
    class: "assassin",
    damageType: "physical",
    slug: "thanatos",
    role: {
      carry: 1,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 2,
    },
  },
  43: {
    id: 43,
    name: "Mercury",
    class: "assassin",
    damageType: "physical",
    slug: "mercury",
    role: {
      carry: 2,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 2,
    },
  },
  44: {
    id: 44,
    name: "Sun Wukong",
    class: "warrior",
    damageType: "physical",
    slug: "sun-wukong",
    role: {
      carry: 1,
      support: 2,
      mid: 1,
      jungle: 3,
      solo: 5,
    },
  },
  45: {
    id: 45,
    name: "Ah Muzen Cab",
    class: "hunter",
    damageType: "physical",
    slug: "ah-muzen-cab",
    role: {
      carry: 5,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 2,
    },
  },
  46: {
    id: 46,
    name: "Nu Wa",
    class: "mage",
    damageType: "magical",
    slug: "nu-wa",
    role: {
      carry: 2,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 3,
    },
  },
  47: {
    id: 47,
    name: "Chaac",
    class: "warrior",
    damageType: "physical",
    slug: "chaac",
    role: {
      carry: 1,
      support: 1,
      mid: 2,
      jungle: 3,
      solo: 5,
    },
  },
  48: {
    id: 48,
    name: "Geb",
    class: "guardian",
    damageType: "magical",
    slug: "geb",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 1,
      solo: 3,
    },
  },
  49: {
    id: 49,
    name: "Nemesis",
    class: "assassin",
    damageType: "physical",
    slug: "nemesis",
    role: {
      carry: 1,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 1,
    },
  },
  50: {
    id: 50,
    name: "Scylla",
    class: "mage",
    damageType: "magical",
    slug: "scylla",
    role: {
      carry: 2,
      support: 1,
      mid: 5,
      jungle: 2,
      solo: 1,
    },
  },
  51: {
    id: 51,
    name: "Ullr",
    class: "hunter",
    damageType: "physical",
    slug: "ullr",
    role: {
      carry: 5,
      support: 1,
      mid: 3,
      jungle: 3,
      solo: 2,
    },
  },
  52: {
    id: 52,
    name: "Kumbhakarna",
    class: "guardian",
    damageType: "magical",
    slug: "kumbhakarna",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 2,
      solo: 2,
    },
  },
  53: {
    id: 53,
    name: "Osiris",
    class: "warrior",
    damageType: "physical",
    slug: "osiris",
    role: {
      carry: 1,
      support: 2,
      mid: 1,
      jungle: 3,
      solo: 5,
    },
  },
  54: {
    id: 54,
    name: "Janus",
    class: "mage",
    damageType: "magical",
    slug: "janus",
    role: {
      carry: 1,
      support: 1,
      mid: 5,
      jungle: 3,
      solo: 1,
    },
  },
  55: {
    id: 55,
    name: "Rama",
    class: "hunter",
    damageType: "physical",
    slug: "rama",
    role: {
      carry: 5,
      support: 1,
      mid: 3,
      jungle: 1,
      solo: 1,
    },
  },
  56: {
    id: 56,
    name: "Serqet",
    class: "assassin",
    damageType: "physical",
    slug: "serqet",
    role: {
      carry: 1,
      support: 4,
      mid: 1,
      jungle: 5,
      solo: 2,
    },
  },
  57: {
    id: 57,
    name: "Cabrakan",
    class: "guardian",
    damageType: "magical",
    slug: "cabrakan",
    role: {
      carry: 1,
      support: 5,
      mid: 2,
      jungle: 4,
      solo: 5,
    },
  },
  58: {
    id: 58,
    name: "Sylvanus",
    class: "guardian",
    damageType: "magical",
    slug: "sylvanus",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 1,
      solo: 1,
    },
  },
  59: {
    id: 59,
    name: "Nox",
    class: "mage",
    damageType: "magical",
    slug: "nox",
    role: {
      carry: 1,
      support: 4,
      mid: 4,
      jungle: 1,
      solo: 1,
    },
  },
  60: {
    id: 60,
    name: "Ao Kuang",
    class: "mage",
    damageType: "magical",
    slug: "ao-kuang",
    role: {
      carry: 1,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 3,
    },
  },
  61: {
    id: 61,
    name: "Awilix",
    class: "assassin",
    damageType: "physical",
    slug: "awilix",
    role: {
      carry: 1,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 2,
    },
  },
  62: {
    id: 62,
    name: "HouYi",
    class: "hunter",
    damageType: "physical",
    slug: "houyi",
    role: {
      carry: 5,
      support: 1,
      mid: 2,
      jungle: 3,
      solo: 1,
    },
  },
  63: {
    id: 63,
    name: "Bellona",
    class: "warrior",
    damageType: "physical",
    slug: "bellona",
    role: {
      carry: 2,
      support: 2,
      mid: 1,
      jungle: 3,
      solo: 5,
    },
  },
  64: {
    id: 64,
    name: "Medusa",
    class: "hunter",
    damageType: "physical",
    slug: "medusa",
    role: {
      carry: 5,
      support: 1,
      mid: 4,
      jungle: 1,
      solo: 1,
    },
  },
  65: {
    id: 65,
    name: "Ah Puch",
    class: "mage",
    damageType: "magical",
    slug: "ah-puch",
    role: {
      carry: 1,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 2,
    },
  },
  66: {
    id: 66,
    name: "Ratatoskr",
    class: "assassin",
    damageType: "physical",
    slug: "ratatoskr",
    role: {
      carry: 2,
      support: 3,
      mid: 2,
      jungle: 5,
      solo: 4,
    },
  },
  67: {
    id: 67,
    name: "Ravana",
    class: "assassin",
    damageType: "physical",
    slug: "ravana",
    role: {
      carry: 1,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 3,
    },
  },
  68: {
    id: 68,
    name: "Khepri",
    class: "guardian",
    damageType: "magical",
    slug: "khepri",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 1,
      solo: 1,
    },
  },
  69: {
    id: 69,
    name: "Xing Tian",
    class: "guardian",
    damageType: "magical",
    slug: "xing-tian",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 2,
      solo: 4,
    },
  },
  70: {
    id: 70,
    name: "Sol",
    class: "mage",
    damageType: "magical",
    slug: "sol",
    role: {
      carry: 5,
      support: 1,
      mid: 3,
      jungle: 1,
      solo: 2,
    },
  },
  71: {
    id: 71,
    name: "Chiron",
    class: "hunter",
    damageType: "physical",
    slug: "chiron",
    role: {
      carry: 5,
      support: 1,
      mid: 4,
      jungle: 1,
      solo: 1,
    },
  },
  72: {
    id: 72,
    name: "Amaterasu",
    class: "warrior",
    damageType: "physical",
    slug: "amaterasu",
    role: {
      carry: 1,
      support: 3,
      mid: 1,
      jungle: 2,
      solo: 5,
    },
  },
  73: {
    id: 73,
    name: "Raijin",
    class: "mage",
    damageType: "magical",
    slug: "raijin",
    role: {
      carry: 2,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 2,
    },
  },
  74: {
    id: 74,
    name: "Skadi",
    class: "hunter",
    damageType: "physical",
    slug: "skadi",
    role: {
      carry: 5,
      support: 1,
      mid: 3,
      jungle: 1,
      solo: 1,
    },
  },
  75: {
    id: 75,
    name: "Jing Wei",
    class: "hunter",
    damageType: "physical",
    slug: "jing-wei",
    role: {
      carry: 5,
      support: 1,
      mid: 1,
      jungle: 1,
      solo: 1,
    },
  },
  76: {
    id: 76,
    name: "Susano",
    class: "assassin",
    damageType: "physical",
    slug: "susano",
    role: {
      carry: 2,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 2,
    },
  },
  77: {
    id: 77,
    name: "Fafnir",
    class: "guardian",
    damageType: "magical",
    slug: "fafnir",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 1,
      solo: 1,
    },
  },
  78: {
    id: 78,
    name: "Erlang Shen",
    class: "warrior",
    damageType: "physical",
    slug: "erlang-shen",
    role: {
      carry: 1,
      support: 3,
      mid: 1,
      jungle: 5,
      solo: 3,
    },
  },
  79: {
    id: 79,
    name: "Terra",
    class: "guardian",
    damageType: "magical",
    slug: "terra",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 1,
      solo: 3,
    },
  },
  80: {
    id: 80,
    name: "Izanami",
    class: "hunter",
    damageType: "physical",
    slug: "izanami",
    role: {
      carry: 5,
      support: 1,
      mid: 3,
      jungle: 1,
      solo: 1,
    },
  },
  81: {
    id: 81,
    name: "Camazotz",
    class: "assassin",
    damageType: "physical",
    slug: "camazotz",
    role: {
      carry: 1,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 5,
    },
  },
  82: {
    id: 82,
    name: "Thoth",
    class: "mage",
    damageType: "magical",
    slug: "thoth",
    role: {
      carry: 2,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 1,
    },
  },
  83: {
    id: 83,
    name: "Nike",
    class: "warrior",
    damageType: "physical",
    slug: "nike",
    role: {
      carry: 1,
      support: 3,
      mid: 1,
      jungle: 3,
      solo: 5,
    },
  },
  84: {
    id: 84,
    name: "The Morrigan",
    class: "mage",
    damageType: "magical",
    slug: "the-morrigan",
    role: {
      carry: 3,
      support: 1,
      mid: 5,
      jungle: 2,
      solo: 2,
    },
  },
  85: {
    id: 85,
    name: "Kuzenbo",
    class: "guardian",
    damageType: "magical",
    slug: "kuzenbo",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 2,
      solo: 3,
    },
  },
  86: {
    id: 86,
    name: "Cernunnos",
    class: "hunter",
    damageType: "physical",
    slug: "cernunnos",
    role: {
      carry: 5,
      support: 1,
      mid: 2,
      jungle: 1,
      solo: 1,
    },
  },
  87: {
    id: 87,
    name: "Ganesha",
    class: "guardian",
    damageType: "magical",
    slug: "ganesha",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 1,
      solo: 1,
    },
  },
  88: {
    id: 88,
    name: "Da Ji",
    class: "assassin",
    damageType: "physical",
    slug: "da-ji",
    role: {
      carry: 1,
      support: 2,
      mid: 1,
      jungle: 5,
      solo: 1,
    },
  },
  89: {
    id: 89,
    name: "Cu Chulainn",
    class: "warrior",
    damageType: "physical",
    slug: "cu-chulainn",
    role: {
      carry: 1,
      support: 2,
      mid: 1,
      jungle: 2,
      solo: 5,
    },
  },
  90: {
    id: 90,
    name: "Artio",
    class: "guardian",
    damageType: "magical",
    slug: "artio",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 1,
      solo: 4,
    },
  },
  91: {
    id: 91,
    name: "Hachiman",
    class: "hunter",
    damageType: "physical",
    slug: "hachiman",
    role: {
      carry: 5,
      support: 1,
      mid: 2,
      jungle: 1,
      solo: 1,
    },
  },
  92: {
    id: 92,
    name: "Discordia",
    class: "mage",
    damageType: "magical",
    slug: "discordia",
    role: {
      carry: 1,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 1,
    },
  },
  93: {
    id: 93,
    name: "Cerberus",
    class: "guardian",
    damageType: "magical",
    slug: "cerberus",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 1,
      solo: 5,
    },
  },
  94: {
    id: 94,
    name: "Achilles",
    class: "warrior",
    damageType: "physical",
    slug: "achilles",
    role: {
      carry: 1,
      support: 3,
      mid: 1,
      jungle: 3,
      solo: 5,
    },
  },
  95: {
    id: 95,
    name: "Chernobog",
    class: "hunter",
    damageType: "physical",
    slug: "chernobog",
    role: {
      carry: 5,
      support: 1,
      mid: 2,
      jungle: 2,
      solo: 1,
    },
  },
  96: {
    id: 96,
    name: "Baron Samedi",
    class: "mage",
    damageType: "magical",
    slug: "baron-samedi",
    role: {
      carry: 1,
      support: 4,
      mid: 4,
      jungle: 1,
      solo: 4,
    },
  },
  97: {
    id: 97,
    name: "Pele",
    class: "assassin",
    damageType: "physical",
    slug: "pele",
    role: {
      carry: 1,
      support: 1,
      mid: 1,
      jungle: 5,
      solo: 1,
    },
  },
  98: {
    id: 98,
    name: "Hera",
    class: "mage",
    damageType: "magical",
    slug: "hera",
    role: {
      carry: 2,
      support: 1,
      mid: 5,
      jungle: 2,
      solo: 1,
    },
  },
  99: {
    id: 99,
    name: "King Arthur",
    class: "warrior",
    damageType: "physical",
    slug: "king-arthur",
    role: {
      carry: 1,
      support: 1,
      mid: 1,
      jungle: 1,
      solo: 5,
    },
  },
  100: {
    id: 100,
    name: "Merlin",
    class: "mage",
    damageType: "magical",
    slug: "merlin",
    role: {
      carry: 2,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 1,
    },
  },
  101: {
    id: 101,
    name: "Jormungandr",
    class: "guardian",
    damageType: "magical",
    slug: "jormungandr",
    role: {
      carry: 1,
      support: 3,
      mid: 3,
      jungle: 1,
      solo: 5,
    },
  },
  102: {
    id: 102,
    name: "Horus",
    class: "warrior",
    damageType: "physical",
    slug: "horus",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 2,
      solo: 2,
    },
  },
  103: {
    id: 103,
    name: "Set",
    class: "assassin",
    damageType: "physical",
    slug: "set",
    role: {
      carry: 3,
      support: 1,
      mid: 3,
      jungle: 5,
      solo: 4,
    },
  },
  104: {
    id: 104,
    name: "Olorun",
    class: "mage",
    damageType: "magical",
    slug: "olorun",
    role: {
      carry: 5,
      support: 1,
      mid: 3,
      jungle: 1,
      solo: 1,
    },
  },
  105: {
    id: 105,
    name: "Persephone",
    class: "mage",
    damageType: "magical",
    slug: "persephone",
    role: {
      carry: 1,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 1,
    },
  },
  106: {
    id: 106,
    name: "Yemoja",
    class: "guardian",
    damageType: "magical",
    slug: "yemoja",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 1,
      solo: 1,
    },
  },
  107: {
    id: 107,
    name: "Heimdallr",
    class: "hunter",
    damageType: "magical | physical",
    slug: "heimdallr",
    role: {
      carry: 5,
      support: 1,
      mid: 3,
      jungle: 1,
      solo: 2,
    },
  },
  108: {
    id: 108,
    name: "Mulan",
    class: "warrior",
    damageType: "physical",
    slug: "mulan",
    role: {
      carry: 1,
      support: 5,
      mid: 1,
      jungle: 3,
      solo: 5,
    },
  },
  109: {
    id: 109,
    name: "Baba Yaga",
    class: "mage",
    damageType: "magical",
    slug: "baba-yaga",
    role: {
      carry: 1,
      support: 1,
      mid: 5,
      jungle: 1,
      solo: 1,
    },
  },
  110: {
    id: 110,
    name: "Cthulhu",
    class: "guardian",
    damageType: "magical",
    slug: "cthulhu",
    role: {
      carry: 1,
      support: 3,
      mid: 2,
      jungle: 1,
      solo: 5,
    },
  },
  111: {
    id: 111,
    name: "Tsukuyomi",
    class: "assassin",
    damageType: "physical",
    slug: "tsukuyomi",
    role: {
      carry: 2,
      support: 1,
      mid: 2,
      jungle: 5,
      solo: 4,
    },
  },
  112: {
    id: 112,
    name: "Danzaburou",
    class: "hunter",
    damageType: "physical",
    slug: "danzaburou",
    role: {
      carry: 5,
      support: 1,
      mid: 2,
      jungle: 2,
      solo: 1,
    },
  },
  113: {
    id: 113,
    name: "Tiamat",
    class: "mage",
    damageType: "magical",
    slug: "tiamat",
    role: {
      carry: 1,
      support: 1,
      mid: 5,
      jungle: 2,
      solo: 2,
    },
  },
};
